/**
 * Novels measured from a copy held locally, rather than fetched from Gutenberg.
 *
 * Generated by `tools/measure-book.ts` — do not edit by hand. Kept in its own
 * file because the Gutenberg harvester rewrites `reference-data.ts` wholesale
 * and would otherwise delete these on its next run.
 *
 * Only the numbers, as everywhere else. No prose from these books is stored or
 * shipped, which is what makes it reasonable to measure books still in
 * copyright: what is kept here could not reconstruct a sentence of one.
 *
 * These sit alongside the public-domain novels and are treated no differently.
 */

import type { ReferenceWork } from "./reference-data.js";

export const LOCAL_WORKS: ReferenceWork[] = [
  {
    "author": "J. P. Moore",
    "title": "Toothless",
    "year": 2010,
    "kind": "Fantasy",
    "words": 95404,
    "dialogueShare": 0.1026,
    "features": {
      "sent.mean": 9.8041,
      "sent.sd": 6.5973,
      "sent.short": 0.2991,
      "sent.long": 0.0142,
      "punct.comma": 0.6776,
      "punct.semicolon": 0.0105,
      "punct.dash": 2.872,
      "punct.exclaim": 0.011,
      "punct.question": 0.0433,
      "para.words": 33.8793,
      "para.single": 0.2891,
      "lex.ttr": 0.58,
      "lex.syllables": 1.2997,
      "lex.latinate": 0.0164,
      "lex.monosyll": 0.7555,
      "open.conjunction": 0.0318,
      "open.participle": 0.0116,
      "open.the": 0.1463,
      "pov.first": 6.9808,
      "pov.third": 95.0589,
      "pov.filtering": 14.3809,
      "pov.past": 0.9628,
      "mod.adverb": 3.4799,
      "mod.intensifier": 3.417,
      "mod.hedge": 4.4547,
      "mod.negation": 11.7081,
      "tag.rate": 8.4273,
      "tag.said": 0.495,
      "tag.adverb": 0,
      "rhythm.syllPerSent": 12.7427
    }
  }
];
